name: Christa-gallery
favicon: null
layout_spectrum: 0
typography_spectrum: 0.003294283291324973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.41499240114353597
  lightness: 0.054738647770136595
  saturation: 0.9551447832491249
  rhythmicContrast: 0.174115450354293
purpose: []
